### ISSUE TITLE
Erro no teste em ClinicaTests.cs>produzirRelatorioTest

### ISSUE THREAD

**Issue by DS-00** [GabrielAgrela/ClinicaVeterinaria#1]
Test Name:    produzirRelatorioTest
Test FullName:    ClinicaVeterinariaTests.ClinicaVeterinaria.Tests.ClinicaTests.produzirRelatorioTest
Test Source:    D:\Github\SO-COVID19SIM\ClinicaVeterinaria\ClinicaVeterinariaTests\ClinicaTests.cs : line 13
Test Outcome:    Failed
Test Duration:    0:00:00

Test Name:    produzirRelatorioTest
Test Outcome:    Failed
Result StackTrace:    at ClinicaVeterinaria.Tests.ClinicaTests.produzirRelatorioTest() in D:\Github\SO-COVID19SIM\ClinicaVeterinaria\ClinicaVeterinariaTests\ClinicaTests.cs:line 73
Result Message:    Assert.AreEqual failed. 
**Expected:<jorge>.** 
**Actual:<
Cliente: jorge 
   Animal: teiomoso 
       Servico: 10€ 2 dias mebocaina dores de garganta1 dr Arroz 
   Animal: scooby 
       Servico: 20€ 3 dias leite dores de garganta2 dr Arroz 
       Servico: 230€ 30 dias anti-inflamatorios dores de garganta3 dr Antonia 
       Servico: 140€ 10 dias mebocaina dores de garganta4 dr Antonia 
   Animal: geremias 
       Servico: 120€ 23 dias mebocain3a dores de garganta5 dr Antonia >. wrong user**

**Comment by GabrielAgrela** [comment]
O teste está correto, o valor esperado é que não foi definido. 
Tenho dúvidas se o valor esperado deveria ser um array (contendo animais, que por sua vez, têm arrays de serviços) ou se deveriamos pôr apenas a string.

**Comment by DS-00** [comment]
Só mais uma coisa quando tava a fazer um comentário no código sobre isso, dizia que não tinha acesso à escrita. Podias verificar se eu tenho acesso à escrita?
